config/routes.rb
Rails.application.routes.draw do
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  resources :line_items, :orders, :customer,
            :batches, :locations, :varieties,
            :line_item_batches
 
  unauthenticated do
    devise_scope :user do
      root to: "devise/sessions#new"
    end
  end

  authenticated do
    root to: 'varieties#index'
  end
end

app/models/variety.rb
class Variety < ApplicationRecord
  belongs_to :container
  has_many :batches
  has_many :line_items

  def total_containers
    batches.sum('quantity')
  end

  def ready_to_ship
    batches.where(stage: '5').sum(&:plants_available)
  end

  def total_plants
    total_containers * container.capacity
  end

  def batch_count
    batches.length
  end

  def total_ordered
    line_items.sum('quantity')
  end

  def total_available
    ready_to_ship - total_ordered
  end

  def available?
    total_available > 0
  end

  def parent_batches
    batches.select{|batch| batch.type == 'parent'}
  end

  def present_parent_batches
    batches.select{|batch| batch.type == 'parent' && batch.plants_available > 0}
  end
end

app/controllers/varieties_controller.rb
class VarietiesController < ApplicationController
  def index
    @varieties = Variety.all
  end

  def show
    @variety = Variety.find(params[:id])
  end

  def new
    @variety = Variety.new
    @containers = Container.all
  end

  def create
    vp = variety_params
    vp[:container] = Container.find(vp[:container])
    @variety = Variety.new(vp)
    if @variety.save
      redirect_to @variety
    end
  end
  private
  def variety_params
    params.require(:variety).permit(:plant_id, :name, :container, :price, :root_time, :ppp, :difficulty, :source, :reorder_amount)
  end
end

app/helpers/variety_helper.rb
module VarietyHelper
end

app/views/varieties/index.html.erb
<h4>Plants   
  <%= link_to new_variety_path do %>
    <%= fa_icon 'plus-square', class: 'btn btn-success' %>
  <% end %>
</h4>


<table class="table table-striped border">
  <thead class="table-primary">
    <tr>
    <th scope="col">Plant Id</th>
      <th scope="col">Name</th>
      <th scope="col">Price</th>
      <th scope="col">Container Type</th>
      <th scope="col">Containers</th>
      <th scope="col">Plants</th>
      <th scope="col">Root Time</th>
      <th scope="col">PPP</th>
      <th scope="col">Difficulty</th>
      <th scope="col">Source</th>
      <th scope="col">Batch Count</th>
      <th scope="col">Reorder Amount</th>
    </tr>
  </thead>
  <tbody>
    <% @varieties.each do |variety| %>
        <tr>
        <td><%= link_to(variety.plant_id, variety) %></td>
        <td><%= variety.name %></td>
        <td><%= number_to_currency(variety.price.to_f / 100)%></td>
        <td><%= variety.container.name %></td>
        <td><%= variety.total_containers %></td>
        <td><%= variety.total_plants %></td>
        <td><%= variety.root_time %></td>
        <td><%= variety.ppp %></td>
        <td><%= variety.difficulty %></td>
        <td><%= variety.source %></td>
        <td><%= variety.batch_count %></td>
        <td><%= variety.reorder_amount %></td>
        </tr>
    <% end %>
  </tbody>
</table>

app/views/varieties/new.html.erb
<div class="container ">
    <div class="card col-md-4">
    <div class="card-header" >New Plant</div>
        <div class="row mx-auto m-3">
            <%= form_for @variety do |f| %>
                <div class="form-group">
                    <label>Plant Id</label></br>
                    <%= f.text_field :plant_id, class: "form-control" %>
                </div>
                <div class="form-group">
                    <label>Name </label> 
                    <%= f.text_field :name, class: "form-control" %>
                </div>
                <div class="form-group">
                    <label>Container Type</label></br> 
                    <%= f.select 'container',  options_from_collection_for_select(@containers, 'id', 'name'),{}, class: "form-control" %>
                </div>
                <div class="form-group">
                    <label>PPP</label></br>
                    <%= f.text_field :ppp, class: "form-control" %>
                </div>
                <div class="form-group">
                    <label>Price in Cents</label></br>
                    <%= f.text_field :price, class: "form-control" %>
                </div>
                <div class="form-group">
                    <label>Weeks to Root</label></br>
                    <%= f.text_field :root_time, class: "form-control" %>
                </div>
                 <div class="form-group">
                    <label>Difficulty</label></br>
                    <%= f.text_field :difficulty, class: "form-control" %>
                </div>
                <div class="form-group">
                    <label>Source</label></br>
                    <%= f.text_field :source, class: "form-control" %>
                </div>
                <div class="form-group">
                    <label>Reorder Amount</label></br>
                    <%= f.text_field :reorder_amount, class: "form-control" %>
                </div>
            <%= f.submit class: "btn btn-primary" %>
            <% end %>
        </div>
    </div>
</div>

app/views/varieties/show.html.erb
<h4><%= @variety.name %></h4>
<div class="row">
  <div >
    <ul class="list-group list-group-horizontal-md">
      <li class="list-group-item list-group-item-success">
          Available: <%= @variety.ready_to_ship - @variety.total_ordered %>
      </li>
      <li class="list-group-item">
          Total Ordered: <%= @variety.total_ordered %>
      </li>
      <li class="list-group-item">
          Stage 5: <%= @variety.ready_to_ship %>
      </li>
      <li class="list-group-item">
          Still Growing: <%= @variety.total_plants - @variety.ready_to_ship %>
      </li>
      <li class="list-group-item">
          On-hand: <%= @variety.total_plants %>
      </li>
    </ul>
    <ul class="list-group list-group-horizontal-md">
        <li class="list-group-item">
            Price: <%= number_to_currency(@variety.price.to_f / 100) %>
        </li>
        <li class="list-group-item">
            Container: <%= @variety.container.name %>
        </li>
        <li class="list-group-item">
            PPP: <%= @variety.ppp %>
        </li>
        <li class="list-group-item">
            Weeks To Root: <%= @variety.root_time %>
        </li>
        <li class="list-group-item">
            Difficulty: <%= @variety.difficulty %>
        </li>
         <li class="list-group-item">
            Source: <%= @variety.source %>
        </li>
        <li class="list-group-item">
            Reorder Amount: <%= @variety.reorder_amount %>
        </li>

    </ul>
  </div>
</div>

<h2 class="mt-5"> Batches </h2>
<table class="table table-striped">
  <thead class="table-success">
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Value</th>
      <th scope="col">Available</th>
      <th scope="col">Stage</th>
      <th scope="col">Planter</th>
      <th scope="col">Location</th>
      <th scope="col">Soil</th>
      <th scope="col">Treatment</th>
    </tr>
  </thead>
  <tbody>
    <% @variety.present_parent_batches.each do |batch| %>
        <tr>
        <td><%= link_to("B"+batch.id.to_s, batch) %></td>
        <td><%= number_to_currency(batch.value)%></td>
        <td><%= batch.plants_available %></td>
        <td><%= batch.stage %></td>
        <td><%= batch.user.email %></td>
        <td><%= link_to(batch.location.name, batch.location) %></td>
        <td><%= batch.soil %></td>
        <td><%= batch.treatment %></td>
        </tr>
    <% end %>
  </tbody>
</table>

<h2 class="mt-5"> Pending Line Items </h2>

<table class="table table-striped">
  <thead class="table-success">
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Value</th>
      <th scope="col">Qty Needed</th>
      <th scope="col">Customer</th>
      <th scope="col">Region</th>
    </tr>
  </thead>
  <tbody>
    <% @variety.line_items.reject(&:shipped?).each do |line| %>
        <tr>
        <td><%= link_to(line.order.po_number, order_url) %></td>
        <td><%= number_to_currency(line.value / 100)%></td>
        <td><%= line.to_ship %></td>
        <td><%= link_to(line.order.customer.name, line.order.customer) %></td>
        <td><%= line.order.customer.region %></td>
        </tr>
    <% end %>
  </tbody>
</table>