config/routes.rb
Rails.application.routes.draw do
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  resources :line_items, :orders, :customer,
            :batches, :locations, :varieties,
            :line_item_batches
 
  unauthenticated do
    devise_scope :user do
      root to: "devise/sessions#new"
    end
  end

  authenticated do
    root to: 'varieties#index'
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer, class_name: 'Customer', foreign_key: 'customer_id'
  belongs_to :billing_customer, class_name: 'Customer', foreign_key: 'billing_customer_id'
  has_many :line_items
  
  validates :po_number, presence: true
  
  def value
    line_items.sum(&:value)
  end

  def shipped?
    line_items.collect(&:shipped?).all?
  end

  def total_line_items
    line_items.length
  end
end

app/controllers/order_controller.rb
class OrderController < ApplicationController
  def create
    op = order_params
    op[:customer] = Customer.find(order_params[:customer])
    op[:billing_customer] = Customer.find(order_params[:billing_customer])
    @order = Order.new(op)
    if @order.save
      flash[:success] = 'Order Saved'
      redirect_to @order
    end
  end

  def show
    @order = Order.find(params[:id])
  end

  def index
    @orders = Order.where(nil)
    @orders = @orders.reject(&:shipped?).sort_by(&:total_line_items).reverse
  end

  def new
    @order = Order.new
    @customers = Customer.all
  end

  private
  def order_params
    params.require(:order).permit(:po_number, :customer, :billing_customer)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :all_customers, only: %i[index new]

  def create
    op = order_params
    op[:customer] = Customer.find(order_params[:customer])
    op[:billing_customer] = Customer.find(order_params[:billing_customer])
    @order = Order.new(op)
    if @order.save
      flash[:success] = 'Order Saved'
      redirect_to @order
    end
  end

  def show
    order = Order.find(params[:id])
    @order = OrderPresenter.new(order)
  end

  def index
    @orders = Order.all
    @orders = @orders.where(customer: params[:customer_id]) unless params[:customer_id].to_i.zero?
    @orders = @orders.select(&:shipped?) if params[:commit] == 'Filter' && !params[:open].present? 
    @orders = @orders.reject(&:shipped?) unless params[:history].present?
  end

  def new
    @order = Order.new
  end

  private

  def order_params
    params.require(:order).permit(:po_number, :customer, :billing_customer)
  end

  def all_customers
    @customers = Customer.all
  end
end

app/helpers/order_helper.rb
module OrderHelper
end

app/views/orders/index.html.erb
<h4>Orders   
  <%= link_to new_order_path do %>
    <%= fa_icon 'plus-square', class: 'btn btn-success' %>
  <% end %>
</h4>

<div class= 'mb-2'>
  <%= form_tag orders_path, method: 'get', class: 'form-inline' do %>
    <%= select_tag :customer_id, content_tag(:option,'All Customers')+options_from_collection_for_select(@customers, :id, :name, params[:customer_id]), class: 'form-control col-md-2 mr-2'  %>
    Show Open?
    <%= check_box_tag :open, 'true', !params[:commit].present? || params[:open].present?, class: 'form-control col-md-1' %>
    Show Shipped?
    <%= check_box_tag :history, 'true', params[:history].present?,  class: 'form-control col-md-1 text-center'%>
    <%= submit_tag "Filter", class: 'form-control col-md-1 btn btn-primary ml-5' %>
  <% end %>
</div>

<table class="table table-striped border">
  <thead class="table-primary">
    <tr>
      <th scope="col">PO Number</th>
      <th scope="col">Customer</th>
      <th scope="col">Line Items</th>
      <th scope="col">Value</th>
      <th scope="col">Region</th>
      <th scope="col">Status</th>
    </tr>
  </thead>
  <tbody>
    <% @orders.each do |order| %>
        <tr>
            <td><%= link_to(order.po_number, order) %></td>
            <td><%= link_to(order.customer.name, order.customer)%></td>
            <td><%= order.line_items.length %></td>
            <td><%=number_to_currency(order.value / 100)%></td>
            <td><%= order.customer.region%></td>
            <td>
              <% if order.shipped? %>
                <span class="badge badge-success">Shipped</span>
              <% else %>
                <span class="badge badge-danger">Pending</span> 
              <% end %>
            </td>
        </tr>
    <% end %>
  </tbody>
</table>

app/views/orders/new.html.erb
<div class="container ">
    <div class="card col-md-4">
    <div class="card-header" >Create a New Order</div>
        <div class="row mx-auto m-3">
            <%= form_for @order, url: orders_path do |f| %>
                <div class="form-group">
                    <label>PO Number</label></br> 
                    <%= f.text_field :po_number,  class: "form-control" %>
                </div> 
                <div class="form-group">
                    <label>Bill To</label></br> 
                    <%= f.select 'billing_customer',  options_from_collection_for_select(@customers, 'id', 'name'), {}, class: "form-control" %>
                </div> 
                <div class="form-group">
                    <label>Ship To</label></br>
                    <%= f.select 'customer',  options_from_collection_for_select(@customers, 'id', 'name'), {}, class: "form-control" %>
                </div>
            <%= f.submit class: "btn btn-primary" %>
            <% end %>
        </div>
    </div>
</div>

app/views/orders/show.html.erb
<h4>Order</h4>
<div class="row">
    <ul class="list-group list-group-horizontal-md">
      <li class="list-group-item list-group-item-success">
        PO Number: <%= @order.po_number%>
      </li>
      <li class="list-group-item">
         <%= @order.created_at %>
      </li>
      <li class="list-group-item">
      <% if @order.shipped? %>
        <td> <span class="badge badge-success">Shipped</span> </td>
      <% else %>
        <td> <span class="badge badge-danger">Pending</span> </td>
      <% end %>
      </li>
      <li class="list-group-item">
        BIll To: <%= link_to(@order.billing_customer.name, @order.billing_customer)%>
      </li>
      <li class="list-group-item">
        Ship To: <%= link_to(@order.customer_name, @order.customer)%>
      </li>
      <li class="list-group-item">
        Ship Via: <%= @order.customer.region%>
      </li>
      </li>
      <li class="list-group-item">
        Value: <%= number_to_currency(@order.value / 100)%>
      </li>
  </ul>
</div>  

<h3 class="mt-5">Line Items 
  <%= link_to new_line_item_path(params: {order: @order}) do %> 
    <%= fa_icon 'plus-square', class: 'btn btn-success' %>
  <% end %>
</h3>

<table class="table table-striped border">
  <thead class="table-success">
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Variety</th>
      <th scope="col">Ordered</th>
      <th scope="col">Ship Week</th>
      <th scope="col">Last Ship Date</th>
      <th scope="col">Shipped</th>
      <th scope="col">Value</th>      
      <th scope="col">Status</th>
      <th scope="col">Ship</th>
    </tr>
  </thead>
  <tbody>
    <% @order.line_items.sort_by{|li| li.shipped? ? 1 : 0}.each do |line| %>
        <tr>
          <td><%= link_to(line.id, line) %></td>
          <td><%= link_to(line.variety.name, line.variety) %></td>
          <td><%= line.quantity%></td>
          <td><%= line.ship_week%></td>
          <td><%= line.last_ship_date%></td>
          <td><%= line.shipped %></td>
          <td><%= number_to_currency(line.value / 100) %></td> 
          <td>         
            <% if line.shipped? %>
                <span class="badge badge-success">Shipped</span>
              </td>
              <td>
                <%= fa_icon 'truck', class: 'btn btn-primary disabled' %>
            <% else %>
                <span class="badge badge-danger">Pending</span>
              </td>
              <td>
              <%= link_to edit_line_item_path(line.id) do %>
                  <%= fa_icon 'truck', class: 'btn btn-primary' %>
              <% end %>
            <% end %>
          </td>
        </tr>
    <% end %>
  </tbody>
</table>