config/routes.rb
Rails.application.routes.draw do
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  resources :line_items, :orders, :customer,
            :batches, :locations, :varieties,
            :line_item_batches
 
  unauthenticated do
    devise_scope :user do
      root to: "devise/sessions#new"
    end
  end

  authenticated do
    root to: 'varieties#index'
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :orders, class_name: 'Order', foreign_key: 'customer_id'
  has_many :billing_orders,
           class_name: 'Order',
           foreign_key: 'billing_customer_id'

  def active_orders
    orders.reject(&:shipped?)
  end

  def active_orders_count
    active_orders.length
  end

  def total_value
    orders.sum(&:value)
  end

  def open_value
    orders.reject(&:shipped?).sum(&:value)
  end
end

app/controllers/customer_controller.rb
class CustomerController < ApplicationController
  def index
    @customers = Customer.all.sort_by(&:active_orders_count).reverse
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def create
    @customer = Customer.new(customer_params)
    if @customer.save
      flash[:success] = 'Customer Saved'
      redirect_to @customer
    end
  end

  def new
    @customer = Customer.new
  end

  private
  def customer_params
    params.require(:customer).permit(:name, :region)
  end
end

app/helpers/customer_helper.rb
module CustomerHelper
end

app/views/customer/index.html.erb
<h4>Customers
  <%= link_to new_customer_path do %>
    <%= fa_icon 'plus-square', class: 'btn btn-success' %>
  <% end %>
</h4>
<table class="table table-striped border">
  <thead class="table-primary">
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Region</th>
      <th scope="col">Open Orders</th>
      <th scope="col">Open Value</th>
    </tr>
  </thead>
  <tbody>
    <% @customers.each do |customer| %>
        <tr>
            <td><%= link_to(customer.name, customer) %></td>
            <td><%= customer.region %></td>
            <td><%= customer.active_orders_count %></td>
            <td> <%= number_to_currency(customer.open_value / 100) %>
        </tr>
    <% end %>
  </tbody>
</table>

app/views/customer/new.html.erb
<div class="container ">
    <div class="card col-md-4">
    <div class="card-header" >Create a New Customer</div>
        <div class="row mx-auto m-3">
            <%= form_for @customer, url: customer_index_path do |f| %>
                <div class="form-group">
                    <label>Name</label></br> 
                    <%= f.text_field :name, class: "form-control" %>
                </div>
                 <div class="form-group">
                    <label>Region</label></br> 
                    <%= f.text_field :region, class: "form-control" %>
                </div>
            <%= f.submit class: "btn btn-primary" %>
            <% end %>
        </div>
    </div>
</div>

app/views/customer/show.html.erb
<h4><%= @customer.name %></h4>


<div class="row">
  <ul class="list-group list-group-horizontal-md">
      <li class="list-group-item">
        <%= @customer.region  %>
      </li>
      <li class="list-group-item">
         Open Value <%= number_to_currency(@customer.total_value / 100) %>
      </li>
      <li class="list-group-item">
         Closed Value <%= number_to_currency(0) %>
      </li>
  </ul>
</div>

<h4> Open Orders  
  <%= link_to new_order_path do %>
      <%= fa_icon 'plus-square', class: 'btn btn-success' %>
  <% end %> 
</h4>
<table class="table table-striped">
  <thead class="table-success">
    <tr>
      <th scope="col">PO Number</th>
      <th scope="col">Line Items</th>
      <th scope="col">Value</th>
    </tr>
  </thead>
  <tbody>
    <% @customer.orders.reject(&:shipped?).each do |order| %>
        <tr>
        <td><%= link_to(order.po_number, order) %></td>
        <td><%= order.line_items.length %></td>
        <td><%= number_to_currency(order.value / 100) %></td>
        </tr>
    <% end %>
  </tbody>
</table>

<h4>Shipped Orders</h4>
<table class="table table-striped">
  <thead class="table-success">
    <tr>
      <th scope="col">PO Number</th>
      <th scope="col">Line Items</th>
      <th scope="col">Value</th>
    </tr>
  </thead>
  <tbody>
    <% @customer.orders.select(&:shipped?).each do |order| %>
        <tr>
        <td><%= link_to(order.po_number, order) %></td>
        <td><%= order.line_items.length %></td>
        <td><%= number_to_currency(order.value / 100) %></td>
        </tr>
    <% end %>
  </tbody>
</table>