config/routes.rb
Rails.application.routes.draw do
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  resources :line_items, :orders, :customer,
            :batches, :locations, :varieties,
            :line_item_batches
 
  unauthenticated do
    devise_scope :user do
      root to: "devise/sessions#new"
    end
  end

  authenticated do
    root to: 'varieties#index'
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Osiris</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" >Osiris</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-between" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <% if user_signed_in? %>
          <li class="<%= params[:controller] == 'varieties' ? 'nav-item, active' : 'nav-item' %>" >
            <%= link_to("Plants", varieties_path, class: 'nav-link')%>
          </li>
          <li class="<%= params[:controller] == 'batches' ? 'nav-item, active' : 'nav-item' %>" >
            <%= link_to("Prod In", batches_path, class:"nav-link")%>
          </li>
          <li class="<%= params[:controller] == 'line_items' ? 'nav-item, active' : 'nav-item' %>" >
            <%= link_to("Prod out", line_items_path, class:"nav-link")%>
          </li>
          <li class="<%= params[:controller] == 'location' ? 'nav-item, active' : 'nav-item' %>" >
            <%= link_to("Locations", locations_path, class:"nav-link")%>
          </li> 
          <li class="<%= params[:controller] == 'order' ? 'nav-item, active' : 'nav-item' %>" >
            <%= link_to("Orders", orders_path, class:"nav-link")%>
          </li> 
          <li class="<%= params[:controller] == 'customer' ? 'nav-item, active' : 'nav-item' %>" >
            <%= link_to("Customers", customer_index_url, class:"nav-link")%>
          </li> 
      </ul> 
      <ul class="navbar-nav">  
        <li class="nav-item">
          <a class='navbar-text'> <%= @temp %>°  </a> 
          <%= fa_icon 'thermometer-half', class: 'mr-5' %>    
        </li> 
        <li class="nav-item">
          <a class='navbar-text'> <%= @humidity %>%  </a> 
          <%= fa_icon 'tint', class: 'mr-5' %>    
        </li>   
        <li class="nav-item">
          <%= link_to('Logout', destroy_user_session_path, method: :delete, class:"nav-link") %>        
        </li>
      </ul>
      <% else %>
      </ul>
      <ul class="navbar-nav">   
        <li class="nav-item">
          <%= link_to('Login', new_user_session_path, class:"nav-link")  %>  
        </li>
      </ul>
      <% end %>
     </div>
  </nav>
  <% if alert || notice %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  <% end %>
  <div class="m-5">
    <%= yield %>
  </div>
  </body>
</html>